### ISSUE TITLE
SwiftCarousel with only one cell

### ISSUE THREAD

**Issue by frranck** [DroidsOnRoids/SwiftCarousel#21]
Hi, If you put only one cell, the SwiftCarousel will start in the middle of it (half right to the left,  half left to the right), and I noticed that it "get stuck" while scrolling to the left after a moment.
Could there be an option no to have the "infinite loop" feature ?

**Comment by sunshinejr** [comment]
Hmm, you think about disabling scrolling method/parameter?

**Comment by frranck** [comment]
@sunshinejr sorry?

**Comment by aocenas** [comment]
@frranck do you mean, when there is only one view in the items array? I think I have similar issue, where  if I have only few items in the carousel (sum of items widths is less than carousel width) it acts a bit weird. It seems that the buffers of 1 copy of items array on each side is not enough for the scrolling math in that case.

**Comment by frranck** [comment]
@aocenas yes, bellow 3, it's buggy

**Comment by aocenas** [comment]
I think this could be easily fixed by having bigger buffer of items on each side, either by some better magic constant, or by measuring the provided item views and making copies until they are at least 3x carousel width or something similar. Making "disable infinite loop" param is probably different kind of decision.

**Comment by frranck** [comment]
@aocenas i'm using 1 item per page...

**Comment by sunshinejr** [comment]
What I think we can do is to disable scrolling (I mean you could drag the item, but you wouldn't be able to scroll) when there aren't any more items on the list that aren't shown. E.g. you have 3 items in array, but you have 3 items per page and it could disable scrolling then. We could even add that as a property?

**Comment by frranck** [comment]
@sunshinejr Yes and we should not see more items in the borders in that situation.

**Comment by sunshinejr** [comment]
Okay, I'm on it.

**Comment by frranck** [comment]
:thumbsup:

**Comment by sunshinejr** [comment]
Closed in favor of #28.
