### ISSUE TITLE
Some of the carousel cells  don't have their layer properties corrects

### ISSUE THREAD

**Issue by frranck** [DroidsOnRoids/SwiftCarousel#22]
Hi;
I noticed some of the carousel cells don't have their cornerRadius set properly; I can see them with proper corners once; but when you keep scrolling I'm seeing the same cells with no cornerRadius.
Could that be an issue with the copyView function ?

```

    /**
     Method to copy UIView using archivizing.

     - returns: Copied UIView (different memory address than current)
     */
    public func copyView() throws -> UIView {
        prepareConstraintsForArchiving()
        guard let view = NSKeyedUnarchiver.unarchiveObjectWithData(NSKeyedArchiver.archivedDataWithRootObject(self)) as? UIView else { throw ArchiveCopyingError.View }
        return view
    }
```

**Comment by sunshinejr** [comment]
Thanks for the issue!

We improved the `copyView()` method in version 0.5, could you try to check if it happens on this version as well?

**Comment by frranck** [comment]
@sunshinejr I'm using the 0.5

**Comment by sunshinejr** [comment]
Oh right, the `copyView()` method can't really copy CALayer. You can use our `itemsFactory()` method, we introduced it after #11 in version 0.5. [Here is an example](https://github.com/DroidsOnRoids/SwiftCarousel/blob/master/Examples/Example2/Example2/ViewController.swift#L24-L29). Sorry for the inconvenience!

**Comment by frranck** [comment]
@sunshinejr I'm not using it; but I suspect the problem is coming because the library using it [line 104 ](https://github.com/DroidsOnRoids/SwiftCarousel/blob/master/Source/SwiftCarousel.swift).

**Comment by sunshinejr** [comment]
@frranck yes, the `copyView()` method does the copy of view because the views are passed it in the array. When you pass it in the closure (and make a new view in it) using `itemsFactory()`, the views can be created from the recipe rather than copy it, which allows you to copy not only the view, but also models & objects (like view models or `CALayer`).

**Comment by frranck** [comment]
@sunshinejr Thanks for the input
