### ISSUE TITLE
Distinguishing between "scrolled to" and "tapped"

### ISSUE THREAD

**Issue by frranck** [DroidsOnRoids/SwiftCarousel#23]
Hi Lukasz,
Is there a way to distinguish between the situation where an item has been scrolled to, and the situation where an item has been tapped ?
I seems selectItem doesn't inform on that that.

**Comment by sunshinejr** [comment]
Hey @frranck, currently not, but it could be added as well. The only question is if we should send 2 notifications, one when you tap, and then after X seconds the selected one? What's your opinion? Cheers! 🎉

**Comment by frranck** [comment]
@sunshinejr Not sure, I would definitely need a flag with the select to inform me  it's the result of a tap, and If a card is already selected, I would also need to be able to know if the user tapped it afterwards.

I guess we would also need to to authorize taps, while scrolling in the cards using shouldRecognizeSimultaneouslyWithGestureRecognizer

**Comment by sunshinejr** [comment]
Hmm, right. We should add the property for protocol method then. Second method also seems cool. Would you be up for making PR, @frranck? :rocket:

**Comment by frranck** [comment]
@sunshinejr OK!

**Comment by frranck** [comment]
@sunshinejr Did you notice the scroll "jumps around" when you do the [self.scrollView.contentOffset.x = newOffsetX] ?(https://github.com/DroidsOnRoids/SwiftCarousel/blob/master/Source/SwiftCarousel.swift#L289) ?

**Comment by frranck** [comment]
@sunshinejr If I tap around while scrolling, the scroll "jumps around suddenly" did you notice that ? What is causing this ? (You can see that in the examples)

**Comment by sunshinejr** [comment]
Hmm, didn't catch that one. I'm kinda busy today, so I can't really check what is happening.. Will make sure to do it ASAP tho. We could add this as another issue rather than discuss it here as well. Thanks tho! 👏

**Comment by sunshinejr** [comment]
This one is already on CocoaPods, I think we can close it for now.
