### ISSUE TITLE
Scrollview "jumps around" when tapped while scrolling.

### ISSUE THREAD

**Issue by frranck** [DroidsOnRoids/SwiftCarousel#24]
Can be seen in the examples.

**Comment by frranck** [comment]
I added a self delegate for the gestureRecognizer and   

```
func gestureRecognizer(_: UIGestureRecognizer,
        shouldRecognizeSimultaneouslyWithGestureRecognizer:UIGestureRecognizer) -> Bool {
            return true
 }
```

Will include it when I push https://github.com/DroidsOnRoids/SwiftCarousel/issues/23

**Comment by irodrigo17** [comment]
Hi @frranck, Thanks for reporting this and for the fix! I'm also experiencing this issue. Any chance you can push your fix for this one before pushing #23? I can also do a PR myself for this one if that works for you.

**Comment by frranck** [comment]
@irodrigo17 Hi, I pushed both already, they're not merged yet.

**Comment by irodrigo17** [comment]
Awesome! Thanks @frranck!
