### ISSUE TITLE
Help UISwipeGestureRecognizer 

### ISSUE THREAD

**Issue by WAUnique** [DroidsOnRoids/SwiftCarousel#27]
Hello
How can I add UISwipeGestureRecognizer to SwiftCarousel?
I want when I swipe left or right, item just scroll 1 item.
Please help.

**Comment by sunshinejr** [comment]
Hey @weuniq! Thanks for filling in the issue! 🎉 

Unfortunately for now you can't really do that. But what comes to my mind is a property, something along the lines `maxItemsPerScroll`, which by default would be -1, which means you can scroll as far as possible, then 0 would be to stop scrolling, and 1 would mean that you can scroll only one item per swipe, 2 for 2 etc. It would also fix our problem with issue #21. What do you think? 🎂

**Comment by irodrigo17** [comment]
@sunshinejr I really like that approach! :+1:

**Comment by sunshinejr** [comment]
Closed in favor of #28.
