### ISSUE TITLE
Changing items during runtime?

### ISSUE THREAD

**Issue by catsynth** [DroidsOnRoids/SwiftCarousel#31]
Hi.
I am trying to update a carousel at runtime after it has already been initiated and rendered by re-assigning the .items property with a new list of views.  Should this work, or is there another method I should be using to update the carousel items while running?

**Comment by catsynth** [comment]
I suppose this is a duplicate of https://github.com/DroidsOnRoids/SwiftCarousel/issues/19?  Please confirm and if so I will close :)

**Comment by sunshinejr** [comment]
Hey @catsynth! Thanks for the issue! 🎉 

Unfortunately you are right - right now you cannot really update the carousel with any native methods. One workaround for now would be creating another instance of carousel (this time with this added new item), select the item that was selected before, and hide the current carousel, and then show the new one. But it can be memory consuming so you need to be careful about that. 

Although! Also this is a duplicate of #19 as you already noticed. If you have any ideas around adding/updating/deleting items in carousel, maybe you want to do a PR with this change, or if you have any feedback around this topic, I would really appreciate that you do it in #19 and close this one.

Thanks again! 🤗

**Comment by catsynth** [comment]
Cool, I'll close this one.  I'll see if I have some ideas for a refactor. :)
