### ISSUE TITLE
Wrong offset in UIStackView

### ISSUE THREAD

**Issue by aocenas** [DroidsOnRoids/SwiftCarousel#5]
I am using this inside a view with autolayout, which si inside a stack view, and this messes up the offset calculations, mostly because of changing frame which is for some layout cycles {0, 0}. I fixed it for this (my) particular use case, but I did not test other use cases so I am not sure if I did not mess something up. If you want to take a look at those changes I can make a PR for them.

**Comment by sunshinejr** [comment]
Yea, sure, you can do PR and I will test that.

**Comment by sunshinejr** [comment]
Closing for now since your PR is merged.
