### ISSUE TITLE
How to disable circular scrolling

### ISSUE THREAD

**Issue by nahouto** [DroidsOnRoids/SwiftCarousel#9]
Hi,
Thank you for this wonderful app !
I would like to disable infinite scrolling, how can I do that ?

Besides, you write in readme that this library works only in iOS 9 but it seems it also works in iOS 8...

Thanks again !

**Comment by sunshinejr** [comment]
Hey! 

Thanks for the kind words :fire: Yeah it should work in iOS 8 as well, that's a mistake in the docs. The library was specifically created to imitate infinite scroll and for now we don't have an option of disabling the infinite scroll. Also I'm not sure if we will have the option in the future, but I will take a look at it. :smile:
